Template update
sanger-tol/sequencecomposition pull request #8
Opened 2023-07-12 07:29 UTC by muffato

Here I've updated the pipeline template from 2.5 to 2.8, one version at a time. I stopped at 2.8 because I felt like the nf-validation stuff that comes in 2.9 still needs to be ironed out.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/sequencecomposition/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-07-12 11:30 UTC, muffato commented
The CI fails when doing the "full" test because there isn't enough space on disk 😁 The regular test does work already.

I'll try to reduce the disk usage, probably by trimming the samplesheet.

2023-08-04 12:49 UTC, muffato commented
Added a few commits to address issues actually found in https://github.com/sanger-tol/ensemblgenedownload/pull/6 and a commit to enable the `cleanup` profile for our Tower tests and close #9

2023-08-09 08:20 UTC, priyanka-surana requested changes
Almost there, a few changes to documentation.

2023-08-09 08:20 UTC, priyanka-surana commented on .github/workflows/sangerfulltest.yml
Can we rename this to match nf-core `test_full` – `test_full_sanger`?

2023-08-09 08:20 UTC, priyanka-surana commented on .github/workflows/sangertest.yml
Same as above

2023-08-09 08:20 UTC, priyanka-surana commented on .nf-core.yml
Can you add Code of Conduct document back and remove here?

2023-08-09 08:20 UTC, priyanka-surana commented on CHANGELOG.md
Can you fix the release version, name and date for v1? Also add information for the next release.

2023-08-11 09:23 UTC, priyanka-surana approved these changes
LGTM 👍🏼 Thanks for making the changes

2023-08-11 10:06 UTC, merged